### ISSUE TITLE
Nhận xét từ thành viên 2 của nhóm 4

### ISSUE THREAD

**Issue by cttho** [IceIce1ce/Final_Project_LTKHDL#2]
1. Em nghĩ là các anh nên thêm phần xem loại dữ liệu tất cả các cột trước khi xử lý các cột numeric và categorical.
2. Ở phần "Feature selection" thì theo em thấy các anh dùng thư viện sklearn để làm và theo em biết thì hình như mình không được dùng nó trong môn học này (tại em có mail thầy lúc làm đồ án rồi).
3. Ở mỗi câu hỏi có ý nghĩa, các anh cần bổ sung lợi ích sau khi trả lời được câu hỏi (có trong slide yêu cầu).

Ngoài những đóng góp trên thì em rất ấn tượng cách trình bày của bọn anh, đặc biệt là github, nhìn rất chuyên nghiệp và cực kỳ đáng để em học hỏi :D

**Comment by stark4079** [comment]
Cảm ơn nhận xét của bạn. Minh đã cập nhật bản mới nhất.
