### ISSUE TITLE
Nhận xét từ thành viên 1 của nhóm 4

### ISSUE THREAD

**Issue by phineasla** [IceIce1ce/Final_Project_LTKHDL#3]
Sau khi bạn Thọ nhóm em đã nhận xét thì các anh cũng đã update, ngoài phần sklearn ra thì em thấy các anh đã trình bày rất chi tiết và cụ thể, nên em cũng không có gì bổ sung

**Comment by IceIce1ce** [comment]
Cảm ơn góp ý của nhóm em.
